#pragma once

#define MASTER_RIGHT
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

/* RGB Light - 1 WS2812 LED per side (2 total) */
#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 2

#undef RGBLIGHT_SPLIT
#define RGBLIGHT_SPLIT

#undef RGBLED_SPLIT
#define RGBLED_SPLIT {1, 1}

#define RGBLIGHT_HUE_STEP  8
#define RGBLIGHT_SAT_STEP  17
#define RGBLIGHT_VAL_STEP  17
#define RGBLIGHT_LIMIT_VAL 255
