#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_MPLY, KC_NO, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RCTL, KC_LCTL, KC_LALT, KC_LGUI, MO(2), KC_ENT, KC_SPC, MO(3), KC_RSFT, KC_RALT, KC_RGUI),
    [1] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_ESC, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC, KC_TAB, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_MPLY, KC_NO, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_RCTL, KC_LCTL, KC_LALT, KC_LGUI, MO(2), KC_ENT, KC_SPC, MO(3), KC_RSFT, KC_RALT, KC_RGUI),
    [2] = LAYOUT(KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_BSPC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_F12, KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE, KC_LSFT, KC_EQL, KC_MINS, KC_PLUS, KC_LCBR, KC_RCBR, KC_MPLY, KC_CAPS, KC_LBRC, KC_RBRC, KC_SCLN, KC_COLN, KC_BSLS, KC_RSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_NO, KC_ENT, KC_SPC, KC_NO, KC_RSFT, KC_RALT, KC_RGUI),
    [3] = LAYOUT(KC_BSPC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_ESC, KC_NO, KC_PSCR, KC_APP, TO(0), TO(1), KC_PGUP, LALT(KC_LEFT), KC_RSFT, LALT(KC_RGHT), LALT(KC_BSPC), KC_BSPC, LGUI(KC_TAB), LGUI(KC_A), LGUI(KC_R), LGUI(KC_S), LGUI(KC_T), KC_NO, KC_PGDN, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_DEL, KC_LSFT, LGUI(KC_Z), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), LGUI(KC_V), KC_MPLY, KC_TRNS, KC_HOME, KC_END, TO(4), KC_NO, LALT(KC_DEL), KC_RCTL, KC_LCTL, KC_LALT, KC_LGUI, KC_NO, KC_ENT, KC_SPC, KC_NO, KC_RSFT, KC_RALT, KC_RGUI),
    [4] = LAYOUT(TO(0), TO(1), KC_NO, KC_NO, DF(0), DF(1), KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_ESC, KC_NO, PDF(0), PDF(1), TO(0), TO(1), KC_PMNS, KC_4, KC_5, KC_6, KC_PSLS, KC_BSPC, KC_TAB, KC_NO, KC_NO, KC_VOLD, KC_MUTE, KC_VOLU, KC_PPLS, KC_1, KC_2, KC_3, KC_PAST, KC_DEL, KC_LSFT, KC_NO, KC_NO, KC_MPRV, KC_TRNS, KC_MNXT, KC_MPLY, KC_NO, KC_PEQL, KC_0, KC_ENT, KC_NO, KC_PEQL, KC_RCTL, KC_LGUI, KC_LALT, KC_LCTL, TO(0), KC_ENT, KC_SPC, TO(0), KC_RSFT, KC_RALT, KC_RGUI)
};

/* -----------------------------------------------------------------------
 * Encoder callbacks
 *
 * Split Sofle has 2 encoders:
 *   index 0 = left knob
 *   index 1 = right knob  (MASTER_RIGHT means right side is USB master)
 *
 * Layer 0/1 (base layers):
 *   Right knob rotate CW  -> brightness up
 *   Right knob rotate CCW -> brightness down
 *   Right knob click       -> cycle hue (handled via KC_MPLY override below)
 *
 * Note: knob "click" is a regular key in the keymap (KC_MPLY position on
 * the right encoder column). We intercept it in process_record_user so
 * that on layers 0 and 1 it cycles the RGB hue instead.
 * ----------------------------------------------------------------------- */

#ifdef RGBLIGHT_ENABLE

bool encoder_update_user(uint8_t index, bool clockwise) {
    uint8_t layer = get_highest_layer(layer_state);

    /* Right encoder = index 1 (right side is master) */
    if (index == 1) {
        if (layer == 0 || layer == 1) {
            if (clockwise) {
                rgblight_increase_val();
            } else {
                rgblight_decrease_val();
            }
            return false;
        }
    }

    /* Left encoder = index 0 — keep default media behaviour */
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
        return false;
    }

    return true;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    uint8_t layer = get_highest_layer(layer_state);

    /* Intercept right-encoder click (KC_MPLY) on base layers to cycle hue */
    if (keycode == KC_MPLY && record->event.pressed) {
        if (layer == 0 || layer == 1) {
            rgblight_increase_hue();
            return false;
        }
    }

    return true;
}

#endif /* RGBLIGHT_ENABLE */


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

